name: Build and Deploy Docusaurus Site

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'  # Update to a more recent version if possible

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy
        env:
          USE_SSH: true
          GH_PAGES_DEPLOY: github-actions[bot]@users.noreply.github.com
          GIT_USER: 'jabratech'
  